### ISSUE TITLE
Usage with node 6

### ISSUE THREAD

**Issue by SamLebarbare** [epsitec-sa/electrum-ws-client#1]
The lib use regenerator for async/await, we must 
`require ('regenerator-runtime/runtime');` (npm i regenerator-runtime)

native WebSocket is missing node side, a compliant websocket object can be provided as global:
`global.WebSocket = require ('websocket').w3cwebsocket;` (npm i websocket)

In node 6 `Promise.defer ()` is deprecated, it can be replaced by:

```
function defer () {
  var deferred = {};
  var promise = new Promise (function (resolve, reject) {
    deferred.resolve = resolve;
    deferred.reject = reject;
  });
  deferred.promise = promise;
  return deferred;
}
```

**Comment by SamLebarbare** [comment]
I have impl. some polyfills in v2.2.2

**Comment by epsitec** [comment]
@SamLebarbare I've no idea how I managed to get my tests working without the global `WebSocket` object defined. I had it at some time, but then apparently removed it because it was no longer needed. But I cannot figure out, how on Earth, I had managed to get this to work inside of Wallaby.js and mocha.
